# -*- coding: utf-8 -*-
"""Ordonnances types DGBI / motilité — générées depuis
~/Downloads/Ordonnances_types_DGBI_motilite.md (spec validée par A. Debourdeau).
Référentiels : ACG/BSG IBS, ACG/AGA gastroparésie, Rome IV, ANMS-CVSA, ATLANTIS.
Contenu HTML (balises b/i/u/ul/li/br autorisées par le sanitizer du site).
"""

HORS_AMM = "<i>Prescription hors AMM à visée neuromodulatrice / symptomatique, conforme aux recommandations internationales.</i>"

DGBI_ITEMS = [
 # ---------------------------------------------------------- pyrosis
 {"name": "Pyrosis fonctionnel — 1ʳᵉ ligne (amitriptyline + alginate)",
  "kw": "functional heartburn laroxyl gaviscon brûlure rétrosternale neuromodulateur",
  "content": "<b>AMITRIPTYLINE (Laroxyl®) 40 mg/mL, solution buvable</b><br>10 mg (10 gouttes) le soir, 1 h avant le coucher ; augmenter par paliers de 5 mg par semaine selon tolérance, jusqu'à 25–50 mg.<br><i>Hors AMM — voir ordonnance « Amitriptyline (LAROXYL) — titration &amp; consignes ». Durée : 8 semaines minimum puis réévaluation.</i><br><br><b>ALGINATE DE SODIUM / BICARBONATE (Gaviscon®), suspension buvable</b><br>1 sachet ou 10 mL après les repas et au coucher, à la demande.<br><i>Symptomatique d'appoint.</i><br><br><i>Mesures associées : éviction tabac/alcool, gestion du stress ; hypnothérapie / TCC dirigée intestin-cerveau si réfractaire.</i>"},
 {"name": "Pyrosis fonctionnel — 2ᵉ ligne (options au choix)",
  "kw": "citalopram venlafaxine prégabaline ISRS IRSN hypersensibilité œsophagienne",
  "content": "<i>Options de 2ᵉ ligne — n'en conserver qu'une :</i><br><br><b>CITALOPRAM 20 mg, comprimé</b> — 1 cp/j le matin, 8–12 semaines puis réévaluation.<br><i>ISRS, hors AMM ; utile si anxiété/hypervigilance. ECG si facteurs de risque de QT long.</i><br><br><b>OU VENLAFAXINE LP 37,5–75 mg, gélule</b> — 1 gélule/j le matin, 8–12 semaines.<br><i>IRSN, hors AMM.</i><br><br><b>OU PRÉGABALINE 75 mg, gélule</b> — 1 gélule matin et soir, 8 semaines.<br><i>Hors AMM ; hypersensibilité viscérale œsophagienne.</i>"},
 # ---------------------------------------------------------- dyspepsie
 {"name": "Dyspepsie fonctionnelle — EPS : IPP 1ʳᵉ ligne",
  "kw": "epigastric pain syndrome ésoméprazole inexium douleur épigastrique",
  "content": "<i>Vérifier au préalable le statut H. pylori — éradication si positif (« test-and-treat »).</i><br><br><b>ÉSOMÉPRAZOLE 40 mg, comprimé gastro-résistant</b><br>1 comprimé le matin à jeun.<br>Durée : 4 à 8 semaines — <i>réévaluer à 8 semaines, ne pas pérenniser en cas d'échec.</i>"},
 {"name": "Dyspepsie fonctionnelle — PDS : dompéridone (≤ 7 jours)",
  "kw": "postprandial distress plénitude satiété précoce motilium prokinétique",
  "content": "<b>DOMPÉRIDONE 10 mg, comprimé</b><br>1 comprimé 15 à 30 minutes avant chacun des 3 repas.<br>Durée : <b>7 jours maximum</b> (cadre ANSM), puis réévaluation.<br><i>Contre-indications : allongement du QT, interactions QT, insuffisance hépatique modérée à sévère ; prudence après 60 ans (ECG).</i>"},
 {"name": "Dyspepsie fonctionnelle — 2ᵉ ligne (options au choix)",
  "kw": "amitriptyline mirtazapine buspirone menthe carvi réfractaire",
  "content": "<i>Dyspepsie réfractaire aux IPP ± prokinétique — n'en conserver qu'une :</i><br><br><b>AMITRIPTYLINE (Laroxyl®) 40 mg/mL, solution buvable</b> — 10 mg (10 gouttes) le soir, augmenter jusqu'à 25 mg ; 8–12 semaines.<br><i>Hors AMM ; surtout si douleur épigastrique (EPS). Voir ordonnance Laroxyl dédiée.</i><br><br><b>OU MIRTAZAPINE 15 mg, comprimé orodispersible</b> — 1 cp le soir, 8 semaines.<br><i>Hors AMM ; à privilégier si plénitude, satiété précoce, nausées, perte de poids.</i><br><br><b>OU MENTHE POIVRÉE + CARVI (huiles essentielles), capsule</b> — 1 capsule ×2/j avant les repas, 4 semaines.<br><br><b>OU BUSPIRONE 10 mg, comprimé</b> — 1 cp ×3/j avant les repas, 4 semaines.<br><i>Relaxant fundique, hors AMM ; ciblé PDS.</i><br><br><i>Mesures associées : fractionnement des repas, réduction des graisses et du volume des repas.</i>"},
 # ---------------------------------------------------------- gastroparésie
 {"name": "Gastroparésie — nausées / vomissements prédominants",
  "kw": "métoclopramide primpéran ondansétron zophren métopimazine vogalène aprépitant mirtazapine vidange gastrique",
  "content": "<i>Socle : repas fractionnés pauvres en graisses/fibres insolubles, équilibre glycémique, arrêt des opioïdes et agonistes GLP-1.</i><br><br><b>1ʳᵉ ligne — MÉTOCLOPRAMIDE 10 mg, comprimé</b><br>1 cp avant les repas (maximum 30 mg/j). Durée : <b>5 jours maximum par cure</b> (ANSM — risque extrapyramidal).<br><br><i>2ᵉ ligne (options) :</i><br><b>ONDANSÉTRON 4 mg</b> — 1 cp ×2–3/j selon poussée. <i>Hors AMM ; ECG si FdR QT.</i><br><b>OU MÉTOPIMAZINE (Vogalène®) 15 mg</b> — 1 ×3/j avant les repas.<br><br><i>3ᵉ ligne (options) :</i><br><b>APRÉPITANT</b> — 125 mg à J1 puis 80 mg/j, cures courtes. <i>Anti-NK1, hors AMM.</i><br><b>OU MIRTAZAPINE 15 mg orodispersible</b> — 1 cp le soir, 8 semaines. <i>Hors AMM ; nausées + satiété précoce + perte de poids.</i>"},
 {"name": "Gastroparésie — plénitude / satiété précoce prédominante",
  "kw": "dompéridone érythromycine motiline prokinétique vidange",
  "content": "<i>Socle : mesures diététiques, équilibre glycémique, arrêt opioïdes / GLP-1.</i><br><br><b>1ʳᵉ ligne — DOMPÉRIDONE 10 mg, comprimé</b><br>1 cp avant les 3 repas. Durée : <b>7 jours maximum</b> (ANSM) puis réévaluation. <i>ECG ; CI si QT long.</i><br><i>Alternative : MÉTOCLOPRAMIDE 10 mg, 1 cp avant les repas, ≤ 5 jours.</i><br><br><b>2ᵉ ligne — ÉRYTHROMYCINE 250 mg, comprimé ou suspension</b><br>3 mg/kg (≈ 125–250 mg) ×3/j avant les repas. Durée : 2–4 semaines (tachyphylaxie) — cures courtes ou discontinues.<br><i>Agoniste motiline, hors AMM.</i>"},
 {"name": "Gastroparésie — forme mixte (nausées + plénitude)",
  "kw": "métoclopramide dompéridone ondansétron érythromycine mirtazapine G-POEM",
  "content": "<b>1ʳᵉ ligne — MÉTOCLOPRAMIDE 10 mg, comprimé</b><br>1 cp avant les repas (max 30 mg/j), <b>≤ 5 jours par cure</b> (ANSM). <i>Double effet prokinétique + antiémétique.</i><br><br><b>2ᵉ ligne — DOMPÉRIDONE 10 mg</b> avant les repas (<b>≤ 7 j</b>) <b>+ ONDANSÉTRON 4 mg</b> ×2/j selon poussée.<br><br><b>3ᵉ ligne — ÉRYTHROMYCINE</b> 3 mg/kg ×3/j (cures courtes) <b>+ MIRTAZAPINE 15 mg</b> le soir (8 semaines).<br><i>Hors AMM ; forme réfractaire avant orientation pylore (G-POEM) / stimulation gastrique — avis expert.</i>"},
 # ---------------------------------------------------------- SII
 {"name": "SII — antispasmodiques (1ʳᵉ ligne douleur, au choix)",
  "kw": "spasfon phloroglucinol mébévérine duspatalin pinavérium dicetel trimébutine debridat colpermin menthe intestin irritable douleur",
  "content": "<i>Antispasmodiques interchangeables — n'en conserver qu'un :</i><br><br><b>PHLOROGLUCINOL 80 mg (Spasfon Lyoc®)</b> — 2 lyocs en cas de crise, maximum 6/j, à la demande.<br><br><b>OU MÉBÉVÉRINE 200 mg LP</b> — 1 cp matin et soir, 20 min avant les repas ; 1 mois renouvelable.<br><br><b>OU PINAVÉRIUM BROMURE 100 mg</b> — 1 cp matin et soir aux repas ; 1 mois renouvelable.<br><br><b>OU TRIMÉBUTINE 200 mg</b> — 1 cp ×3/j avant les repas ; 1 mois renouvelable.<br><br><b>OU MENTHE POIVRÉE (Colpermin®), capsule gastro-résistante</b> — 1 capsule ×3/j avant les repas ; 4 semaines.<br><br><i>Socle : éducation, régime pauvre en FODMAP encadré (essai limité puis réintroduction), activité physique.</i>"},
 {"name": "SII-D — 1ʳᵉ ligne (lopéramide + antispasmodique)",
  "kw": "diarrhée imodium lopéramide intestin irritable",
  "content": "<b>LOPÉRAMIDE 2 mg, gélule</b><br>1 gélule après chaque selle liquide (maximum 6–8/j), ou 1–2 gélules en préventif avant situation à risque. À la demande — <i>à titrer ; ne traite pas la douleur.</i><br><br><b>+ ANTISPASMODIQUE</b> (voir ordonnance « SII — antispasmodiques ») pour la douleur associée."},
 {"name": "SII-D — 2ᵉ / 3ᵉ ligne (options au choix)",
  "kw": "amitriptyline colestyramine questran ondansétron rifaximine ATLANTIS acides biliaires",
  "content": "<i>Options — n'en conserver qu'une :</i><br><br><b>AMITRIPTYLINE (Laroxyl®) 40 mg/mL</b> — 10 mg (10 gouttes) le soir, augmenter jusqu'à 30 mg ; 6 mois.<br><i>2ᵉ ligne de référence (essai ATLANTIS) ; effet anticholinergique favorable dans le SII-D. Hors AMM — voir ordonnance Laroxyl dédiée.</i><br><br><b>OU COLESTYRAMINE (Questran®) 4 g, sachet</b> — 1 sachet ×1–3/j ; 1 mois d'épreuve.<br><i>Si malabsorption des acides biliaires suspectée.</i><br><br><b>OU ONDANSÉTRON 4 mg</b> — 1 cp ×1–2/j à titrer selon transit. <i>Hors AMM (BSG).</i><br><br><b>OU RIFAXIMINE 550 mg</b> — 1 cp ×2/j, 14 jours. <i>Hors AMM en France (AMM = encéphalopathie hépatique).</i>"},
 {"name": "SII-C — 1ʳᵉ ligne (fibres / macrogol + antispasmodique)",
  "kw": "constipation ispaghul psyllium spagulax forlax macrogol intestin irritable",
  "content": "<b>ISPAGHUL (Spagulax® / psyllium), sachet</b><br>1 sachet ×1–2/j dans un grand verre d'eau, au long cours — <i>fibres solubles, augmenter progressivement.</i><br><br><b>ET/OU MACROGOL 4000 (Forlax® 10 g), sachet</b><br>1 à 2 sachets/j, au long cours — <i>laxatif osmotique.</i><br><br><b>+ ANTISPASMODIQUE</b> (voir ordonnance « SII — antispasmodiques ») pour la douleur."},
 {"name": "SII-C — 2ᵉ ligne (linaclotide, prucalopride)",
  "kw": "constella resolor sécrétagogue 5-HT4",
  "content": "<b>LINACLOTIDE (Constella®) 290 µg, gélule</b><br>1 gélule/j, 30 minutes avant le petit-déjeuner. Réévaluation à 4 semaines.<br><i>AMM : SII-C modéré à sévère. Arrêt si diarrhée sévère.</i><br><br><b>OU PRUCALOPRIDE (Resolor®) 2 mg, comprimé</b> — 1 cp/j, réévaluation à 4 semaines.<br><i>Hors AMM dans le SII (AMM = constipation chronique) ; option si composante transit prédominante.</i>"},
 {"name": "SII-M (mixte) — prise en charge",
  "kw": "intestin irritable alternance duloxétine amitriptyline",
  "content": "<b>ANTISPASMODIQUE</b> selon symptômes (voir ordonnance « SII — antispasmodiques ») ; 1 mois renouvelable — <i>pilier douleur.</i><br><br><b>± Régulateur ciblé à la demande</b> : LOPÉRAMIDE 2 mg à la demande (phases diarrhéiques) / MACROGOL 4000 à la demande (phases constipées).<br><i>Éviter les agents à effet unidirectionnel fort en continu.</i><br><br><i>2ᵉ ligne :</i><br><b>AMITRIPTYLINE (Laroxyl®) 40 mg/mL</b> — 10 mg le soir, augmenter à 20–30 mg ; 6 mois. <i>Hors AMM — voir ordonnance Laroxyl.</i><br><b>OU DULOXÉTINE 30 mg</b> — 1 gélule/j, 8–12 semaines. <i>IRSN, hors AMM ; si anxiété ou TCA mal tolérée.</i>"},
 # ---------------------------------------------------------- Laroxyl dédié
 {"name": "Amitriptyline (LAROXYL) — titration + consignes patient",
  "kw": "laroxyl tricyclique neuromodulateur TCA douleur viscérale titration gouttes",
  "content": "<b>AMITRIPTYLINE (Laroxyl®) 40 mg/mL, solution buvable en gouttes</b> (1 goutte = 1 mg)<br><b>Titration</b> : semaine 1 = 10 mg (10 gouttes) le soir · semaine 2 = 15 mg · semaine 3 = 20 mg · puis paliers de 5 mg/semaine selon tolérance et efficacité.<br><b>Dose cible : 20–30 mg/j</b> (maximum 50 mg/j dans cette indication).<br>Durée : 6 mois puis réévaluation — QSP 3 mois, à renouveler 1 fois.<br><br><i>Prescription hors AMM à visée neuromodulatrice (antalgique viscérale) et non antidépressive — dose très inférieure aux doses psychiatriques.</i><br><br><b><u>Règles de prise et consignes (patient)</u></b><ul><li>Prise <b>le soir</b>, 1 à 2 h avant le coucher.</li><li><b>Titration lente</b> : paliers hebdomadaires ; l'efficacité s'installe en <b>4 à 6 semaines</b>.</li><li>Effets fréquents et transitoires (1–2 semaines) : bouche sèche, somnolence, constipation, vision trouble → s'atténuent, ne pas arrêter pour ce motif.</li><li>Bouche sèche : hydratation, chewing-gum sans sucre. Constipation : hydratation, fibres ± macrogol.</li><li><b>Ne pas conduire</b> en début de traitement.</li><li><b>Ne pas arrêter brutalement</b> (diminution progressive).</li><li>Éviter l'alcool ; prudence avec les autres sédatifs.</li><li>Consulter si : palpitations, malaise, rétention d'urine, confusion.</li></ul><i>Avant prescription : vérifier glaucome à angle fermé, adénome prostatique/rétention urinaire, IDM récent/trouble du rythme, QT long, IMAO. ECG préalable si &gt; 65 ans, cardiopathie ou dose élevée / co-prescriptions QT.</i>"},
 # ---------------------------------------------------------- constipation
 {"name": "Constipation de transit — 1ʳᵉ ligne (macrogol / ispaghul)",
  "kw": "forlax spagulax psyllium lactulose duphalac laxatif osmotique fibres",
  "content": "<b>MACROGOL 4000 (Forlax® 10 g), sachet</b><br>1 sachet le matin ; augmenter à 2/j si besoin. Au long cours — <i>osmotique de référence, 1ʳᵉ intention.</i><br><br><b>ET/OU ISPAGHUL (Spagulax® / psyllium), sachet</b><br>1 sachet ×1–2/j dans un grand verre d'eau, au long cours — <i>à distance des autres médicaments.</i><br><br><i>Alternative osmotique : LACTULOSE (Duphalac®) 15–30 mL le matin (peut majorer les ballonnements).</i><br><br><i>Mesures associées : hydratation ≥ 1,5 L/j, fibres progressives, activité physique régulière.</i>"},
 {"name": "Constipation de transit — 2ᵉ ligne (prucalopride, bisacodyl…)",
  "kw": "resolor stimulant dulcolax picosulfate échec laxatifs",
  "content": "<i>Après échec des osmotiques bien conduits — options :</i><br><br><b>PRUCALOPRIDE (Resolor®) 2 mg, comprimé</b> — 1 cp/j (1 mg si &gt; 65 ans ou insuffisance rénale). Réévaluation à 4 semaines.<br><i>Agoniste 5-HT4 ; AMM constipation chronique après échec des laxatifs.</i><br><br><b>OU LINACLOTIDE (Constella®) 290 µg</b> — 1 gélule/j avant le petit-déjeuner. <i>AMM SII-C uniquement — seulement si douleur/ballonnements associés.</i><br><br><b>OU BISACODYL 5 mg (ou PICOSULFATE)</b> — 1–2 cp le soir, <b>usage intermittent</b> (2–3×/semaine).<br><i>Stimulant ; pas d'usage continu prolongé sans réévaluation.</i>"},
 {"name": "Dyschésie / constipation terminale — RHD + traitements locaux",
  "kw": "évacuation anisme biofeedback eductyl glycérine microlax normacol dyssynergie poussée",
  "content": "<b><u>Mesures hygiéno-diététiques — trouble de l'évacuation</u></b><ul><li>Se présenter à la selle à <b>heure fixe</b>, idéalement <b>20–30 min après un repas</b> (réflexe gastro-colique) ; <b>ne jamais différer</b> le besoin.</li><li><b>Position physiologique</b> : pieds surélevés (marchepied), buste penché en avant, genoux au-dessus des hanches.</li><li>Poussée douce sans blocage respiratoire (éviter le Valsalva prolongé) ; expiration lèvres pincées.</li><li>Hydratation ≥ 1,5 L/j ; fibres progressives ; activité physique.</li><li>Temps aux toilettes limité (&lt; 5 min), sans écran.</li></ul><b>SUPPOSITOIRE EXONÉRATEUR (Eductyl® effervescent)</b> — 1 suppositoire le matin au moment du besoin, à la demande.<br><b>OU GLYCÉRINE, suppositoire adulte</b> — 1 suppositoire au besoin.<br><b>OU SORBITOL + CITRATE (Microlax®)</b> — 1 unidose au moment du besoin.<br><br><i>2ᵉ ligne : lavement DOCUSATE + SORBITOL (Normacol®) ponctuel · MACROGOL 4000 1–2 sachets/j si composante mixte.</i><br><br><b>RÉÉDUCATION ANO-RECTALE / BIOFEEDBACK</b> — 10 à 15 séances.<br><i>Traitement de fond de la dyssynergie (anisme) — kinésithérapeute / service spécialisé.</i>"},
 # ---------------------------------------------------------- SVC
 {"name": "SVC — prophylaxie (amitriptyline ± 2ᵉ ligne)",
  "kw": "vomissements cycliques cyclic vomiting topiramate aprépitant propranolol coenzyme Q10 riboflavine migraine cannabis",
  "content": "<i>Éliminer un syndrome cannabinoïde (CHS) ; dépister et traiter migraine, anxiété, troubles du sommeil.</i><br><br><b>1ʳᵉ ligne — AMITRIPTYLINE (Laroxyl®) 40 mg/mL, solution buvable</b><br>10 mg (10 gouttes) le soir ; augmenter par paliers de 10 mg/semaine ; <b>cible 50–75 mg/j</b> (dose plus élevée que dans le SII). Durée : 6–12 mois.<br><i>Hors AMM. ECG préalable recommandé aux doses ≥ 50 mg. Voir consignes ordonnance Laroxyl.</i><br><br><i>2ᵉ ligne (options, cumulables) :</i><br><b>TOPIRAMATE 25 mg</b> — 25 mg le soir, augmenter jusqu'à 100–150 mg/j en 2 prises ; 6–12 mois. <i>EI cognitifs/paresthésies fréquents.</i><br><b>OU APRÉPITANT 125 mg</b> — 125 mg tous les 2 jours (schémas variables). <i>Anti-NK1 ; réfractaire aux TCA.</i><br><b>OU PROPRANOLOL LP 40–80 mg</b> — 1 cp/j, 6 mois. <i>Surtout si migraine associée.</i><br><b>± COENZYME Q10 + RIBOFLAVINE 400 mg (± L-carnitine)</b> — en continu. <i>Adjuvant à faible risque.</i>"},
 {"name": "SVC — traitement de crise (abortif)",
  "kw": "vomissements cycliques sumatriptan imigrane ondansétron aprépitant crise réhydratation",
  "content": "<b>SUMATRIPTAN 50 mg, comprimé</b> (ou 6 mg SC / spray nasal)<br>Dès les prodromes ; à renouveler 1 fois après 2 h si besoin. <i>Si terrain migraineux — abortif de 1ʳᵉ intention.</i><br><br><b>+ ONDANSÉTRON 4–8 mg, comprimé / lyoc</b> — 4–8 mg ×2–3/j pendant la crise. <i>ECG si FdR QT.</i><br><br><b>± APRÉPITANT</b> — 125 mg à J1 puis 80 mg à J2–J3 (3 jours par crise). <i>Nausées réfractaires.</i><br><br><b>RÉHYDRATATION</b> — soluté de réhydratation orale ; si sévère : soluté glucosé IV (G10) aux urgences.<br><i>Protocole de crise individualisé à partager avec les urgences.</i>"},
]
